[
    {
        "last_connected_at": "2025-11-09T05:50:41.991Z",
        "address": {
            "line_1": "4 Leake Court",
            "city": "Leschenault",
            "state": "Western Australia",
            "postal_code": "6233",
            "country": "AU",
        },
        "water_sense_mode": "auto",
        "timezone": {
            "dst_offset": 0,
            "raw_offset": 28800,
            "timezone_id": "Australia/Perth",
            "timezone_name": "Australian Western Standard Time",
        },
        "full_location": {
            "types": ["premise"],
            "place_id": "ChIJrbf4jO_8MSoRG7mBtW6pt38",
            "geometry": {
                "viewport": {
                    "southwest": {"lng": 115.7211302197085, "lat": -33.26387803029149},
                    "northeast": {"lng": 115.7238281802915, "lat": -33.2611800697085},
                },
                "location_type": "ROOFTOP",
                "location": {"lng": 115.7225234, "lat": -33.262722},
                "bounds": {
                    "southwest": {"lng": 115.7223595, "lat": -33.2628827},
                    "northeast": {"lng": 115.7226972, "lat": -33.2625922},
                },
            },
            "formatted_address": "4 Leake Ct, Leschenault WA 6233, Australia",
            "address_components": [
                {"types": ["street_number"], "short_name": "4", "long_name": "4"},
                {
                    "types": ["route"],
                    "short_name": "Leake Ct",
                    "long_name": "Leake Court",
                },
                {
                    "types": ["locality", "political"],
                    "short_name": "Leschenault",
                    "long_name": "Leschenault",
                },
                {
                    "types": ["administrative_area_level_2", "political"],
                    "short_name": "Harvey",
                    "long_name": "Shire of Harvey",
                },
                {
                    "types": ["administrative_area_level_1", "political"],
                    "short_name": "WA",
                    "long_name": "Western Australia",
                },
                {
                    "types": ["country", "political"],
                    "short_name": "AU",
                    "long_name": "Australia",
                },
                {"types": ["postal_code"], "short_name": "6233", "long_name": "6233"},
            ],
        },
        "weather_forecast_location_id": "5a302b224f0cd78da02baa72",
        "firmware_version": "0096",
        "name": "East",
        "type": "sprinkler_timer",
        "battery": None,
        "network_interface": "wifi",
        "restricted_frequency": {
            "type": "days",
            "days": [0, 1, 2, 3, 4, 5, 6],
            "restricted_times": [{"start_time": "22:00", "stop_time": "07:30"}],
        },
        "weather_delay_thresholds": {
            "precip_prob": 30,
            "precip_in": 0.125,
            "wind_speed_mph": 20,
            "freeze_temp_f": 37,
        },
        "updated_at": "2025-11-09T05:54:58.613Z",
        "reference": "446755a01bc7",
        "mac_address": "446755a01bc7",
        "weather_station_id": None,
        "mesh_id": "63fc75f24f0cb9929eac5ca3",
        "status": {
            "run_mode": "manual",
            "next_start_programs": ["a"],
            "rain_delay_overridden_at": "2025-01-03T07:14:57.512Z",
            "watering_status": {
                "stations": [{"run_time": 10.0, "station": 6}],
                "current_station": 6,
                "water_event_index": None,
                "session_id": None,
                "water_event_queue": [{"station": 6, "run_time_sec": 600}],
                "status": "watering_in_progress",
                "current_time_remaining_sec": 600,
                "rain_sensor_hold": False,
                "program": None,
                "started_watering_station_at": "2025-11-09T05:54:56.000Z",
                "total_run_time_sec": 600,
                "water_instance_id": None,
            },
            "status_updated_at": "2025-11-09T05:54:58.613Z",
            "next_start_time": "2025-11-10T08:00:00+08:00",
            "watering-status": None,
        },
        "wifi_version": 0,
        "id": "63fc75f24f0cb9929eac5ca1",
        "num_stations": 6,
        "zones": [
            {
                "station": 1,
                "name": "Lawn",
                "num_sprinklers": 0,
                "catch_cup_volumes": [],
                "catch_cup_run_time": 0,
                "smart_watering_enabled": False,
            },
            {
                "station": 3,
                "slope_grade": 0,
                "sun_shade": "mostly_shady",
                "name": "Front Garden Beds",
                "landscape_type": "annual_flowers",
                "image_url": "https://s3-us-west-2.amazonaws.com/orbit-irrigation/zone-assets/63fc75d74f0cb9929eac5ca0/304b5604-7af5-4700-9103-220caeac5537",
                "num_sprinklers": 30,
                "soil_type": "loam",
                "catch_cup_volumes": [],
                "catch_cup_run_time": 0,
                "smart_watering_enabled": False,
                "sprinkler_type": "drip",
            },
            {
                "station": 4,
                "slope_grade": 4,
                "sun_shade": "mostly_shady",
                "name": "Front East Bush",
                "landscape_type": "trees",
                "image_url": "https://s3-us-west-2.amazonaws.com/orbit-irrigation/zone-assets/63fc75d74f0cb9929eac5ca0/896b2618-4e8f-444e-b300-a3a8b23ffef2",
                "num_sprinklers": 30,
                "soil_type": "sandy_loam",
                "catch_cup_volumes": [],
                "catch_cup_run_time": 0,
                "smart_watering_enabled": False,
                "sprinkler_type": "spray",
            },
            {
                "station": 5,
                "slope_grade": 0,
                "sun_shade": "mostly_sunny",
                "name": "Citrus Trees 01",
                "landscape_type": "trees",
                "image_url": "https://s3-us-west-2.amazonaws.com/orbit-irrigation/zone-assets/63fc75d74f0cb9929eac5ca0/4316ab13-b88d-41f0-a724-1e943cbe7f44",
                "num_sprinklers": 1,
                "soil_type": "sandy",
                "catch_cup_volumes": [],
                "catch_cup_run_time": 0,
                "smart_watering_enabled": False,
                "sprinkler_type": "spray",
            },
            {
                "station": 6,
                "slope_grade": 0,
                "sun_shade": "mostly_shady",
                "name": "Citrus Trees 02",
                "landscape_type": "trees",
                "image_url": "https://s3-us-west-2.amazonaws.com/orbit-irrigation/zone-assets/63fc75d74f0cb9929eac5ca0/dfbf2bc7-e10f-4b3a-a7f4-68bd8c3c7f02",
                "num_sprinklers": 1,
                "soil_type": "sandy",
                "catch_cup_volumes": [],
                "catch_cup_run_time": 0,
                "smart_watering_enabled": False,
                "sprinkler_type": "spray",
            },
        ],
        "user_id": "63fc75d74f0cb9929eac5ca0",
        "google_home_status": None,
        "device_gateway_topic": "devices-14",
        "smart_watering_enabled": True,
        "hardware_version": "WT25G2-0001",
        "is_connected": True,
        "location": {"type": "Point", "coordinates": [115.7225234, -33.262722]},
        "created_at": "2023-02-27T09:20:50.137Z",
        "suggested_start_time": None,
        "et_id": "5644ff76ad27a7777fff6ecb",
    },
    {
        "last_connected_at": "2025-11-09T03:37:27.105Z",
        "address": {
            "line_1": "4 Leake Court",
            "city": "Leschenault",
            "state": "WA",
            "postal_code": "6233",
            "country": "AU",
        },
        "water_sense_mode": "auto",
        "timezone": {
            "dst_offset": 0,
            "raw_offset": 28800,
            "timezone_id": "Australia/Perth",
            "timezone_name": "Australian Western Standard Time",
        },
        "full_location": {
            "address_components": [
                {"long_name": "4", "short_name": "4", "types": ["street_number"]},
                {
                    "long_name": "Leake Court",
                    "short_name": "Leake Ct",
                    "types": ["route"],
                },
                {
                    "long_name": "Leschenault",
                    "short_name": "Leschenault",
                    "types": ["locality", "political"],
                },
                {
                    "long_name": "Shire of Harvey",
                    "short_name": "Harvey",
                    "types": ["administrative_area_level_2", "political"],
                },
                {
                    "long_name": "Western Australia",
                    "short_name": "WA",
                    "types": ["administrative_area_level_1", "political"],
                },
                {
                    "long_name": "Australia",
                    "short_name": "AU",
                    "types": ["country", "political"],
                },
                {"long_name": "6233", "short_name": "6233", "types": ["postal_code"]},
            ],
            "formatted_address": "4 Leake Ct, Leschenault WA 6233, Australia",
            "geometry": {
                "bounds": {
                    "northeast": {"lat": -33.2626213, "lng": 115.7227091},
                    "southwest": {"lat": -33.2629061, "lng": 115.7223728},
                },
                "location": {"lat": -33.262722, "lng": 115.7225234},
                "location_type": "ROOFTOP",
                "viewport": {
                    "northeast": {"lat": -33.2611917697085, "lng": 115.7238341302915},
                    "southwest": {"lat": -33.2638897302915, "lng": 115.7211361697085},
                },
            },
            "place_id": "ChIJrbf4jO_8MSoRG7mBtW6pt38",
            "types": ["premise"],
        },
        "weather_forecast_location_id": "5a302b224f0cd78da02baa72",
        "firmware_version": "0096",
        "name": "West",
        "type": "sprinkler_timer",
        "network_interface": "wifi",
        "restricted_frequency": None,
        "weather_delay_thresholds": {
            "precip_prob": 30,
            "precip_in": 0.125,
            "wind_speed_mph": 20,
            "freeze_temp_f": 37,
        },
        "updated_at": "2025-11-09T03:38:19.840Z",
        "reference": "446755a061ba",
        "mac_address": "446755a061ba",
        "weather_station_id": None,
        "mesh_id": "6534dc086cfa0233df8b0a59",
        "status": {
            "run_mode": "auto",
            "next_start_programs": ["d"],
            "rain_delay_overridden_at": "2025-01-03T07:15:24.958Z",
            "watering_statuses": [],
            "watering_status": None,
            "status_updated_at": "2025-11-09T03:38:19.466Z",
            "next_start_time": "2025-11-10T07:00:00+08:00",
            "watering-status": None,
        },
        "wifi_version": 0,
        "id": "6534dc076cfa0233df8b0a56",
        "num_stations": 6,
        "zones": [
            {
                "station": 1,
                "name": "1 Dingus",
                "image_url": "https://s3-us-west-2.amazonaws.com/orbit-irrigation/zone-assets/63fc75d74f0cb9929eac5ca0/63f78c77-bffa-42f6-81ff-ba526cc0b613",
                "num_sprinklers": 0,
                "catch_cup_volumes": [],
                "catch_cup_run_time": 0,
                "smart_watering_enabled": False,
            },
            {
                "station": 2,
                "name": "2 Dingus",
                "image_url": "https://s3-us-west-2.amazonaws.com/orbit-irrigation/zone-assets/63fc75d74f0cb9929eac5ca0/7d8d8486-6d5e-43ad-9872-9133095b008c",
                "num_sprinklers": 0,
                "catch_cup_volumes": [],
                "catch_cup_run_time": 0,
                "smart_watering_enabled": False,
            },
            {
                "station": 3,
                "name": "3 Dingus",
                "image_url": "https://s3-us-west-2.amazonaws.com/orbit-irrigation/zone-assets/63fc75d74f0cb9929eac5ca0/fefb4b97-fd4c-44a9-8a56-d93c1db4a823",
                "num_sprinklers": 0,
                "catch_cup_volumes": [],
                "catch_cup_run_time": 0,
                "smart_watering_enabled": False,
            },
            {
                "station": 4,
                "name": "4 Dingus",
                "image_url": "https://s3-us-west-2.amazonaws.com/orbit-irrigation/zone-assets/63fc75d74f0cb9929eac5ca0/85e63685-5a8b-4080-ae10-94339a3efe3c",
                "num_sprinklers": 0,
                "catch_cup_volumes": [],
                "catch_cup_run_time": 0,
                "smart_watering_enabled": False,
            },
        ],
        "user_id": "63fc75d74f0cb9929eac5ca0",
        "google_home_status": None,
        "device_gateway_topic": "devices-12",
        "smart_watering_enabled": True,
        "hardware_version": "WT25G2-0001",
        "is_connected": True,
        "location": {"type": "Point", "coordinates": [115.7225234, -33.262722]},
        "created_at": "2023-10-22T08:23:35.622Z",
        "suggested_start_time": None,
        "et_id": "5644ff76ad27a7777fff6ecb",
    },
]
